apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: cluster-operators
  namespace: openshift-gitops
spec:
  description: Operator apps deployed per cluster
  sourceRepos:
    - https://github.com/dbirenfe/argocd-hierarchy.git
  destinations:
    - namespace: '*'
      server: '*'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
