apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: staging-cluster
  namespace: openshift-gitops
  labels:
    hierarchy/tier: cluster
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: cluster-operators
  source:
    repoURL: https://github.com/dbirenfe/argocd-hierarchy.git
    targetRevision: main
    path: operators/overlays/staging-cluster
  destination:
    server: https://kubernetes.default.svc
    namespace: openshift-gitops
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
