apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: local-cluster-openshift-gitops
  namespace: openshift-gitops
  labels:
    cluster: local-cluster
    tier: operator
    operator: openshift-gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: http://git-server.git-server.svc.cluster.local:8080/argocd-hierarchy.git
    targetRevision: main
    path: resources/openshift-gitops
  destination:
    server: https://kubernetes.default.svc
    namespace: openshift-gitops-operator
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
