apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: staging-cluster-cert-manager
  namespace: openshift-gitops
  labels:
    cluster: staging-cluster
    tier: operator
    operator: cert-manager
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: operators
  source:
    repoURL: https://github.com/dbirenfe/argocd-hierarchy.git
    targetRevision: main
    path: resources/cert-manager
  destination:
    server: https://api.staging-cluster.example.com:6443
    namespace: cert-manager-operator
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
