apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  hierarchy/tier: operator
  hierarchy/cluster: staging-cluster

resources:
  - cert-manager.yaml
  - cluster-logging.yaml
