apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: staging-cluster-

resources:
  - ../../base

patches:
  - target:
      kind: Application
    patch: |
      - op: replace
        path: /spec/destination/server
        value: https://api.staging-cluster.example.com:6443
      - op: add
        path: /metadata/labels/hierarchy~1cluster
        value: staging-cluster
